insert into public.breeds (type, name)
values
  ('cattle', 'Gir'),
  ('cattle', 'Sahiwal'),
  ('cattle', 'Red Sindhi'),
  ('cattle', 'Tharparkar'),
  ('cattle', 'Rathi'),
  ('cattle', 'Kankrej'),
  ('cattle', 'Ongole'),
  ('cattle', 'Hariana'),
  ('cattle', 'Kangayam'),
  ('cattle', 'Bargur'),
  ('cattle', 'Dangi'),
  ('cattle', 'Deoni'),
  ('cattle', 'Khillari'),
  ('cattle', 'Krishna Valley'),
  ('cattle', 'Amritmahal'),
  ('cattle', 'Hallikar'),
  ('cattle', 'Malnad Gidda'),
  ('cattle', 'Vechur'),
  ('cattle', 'Punganur'),
  ('cattle', 'Kasaragod Dwarf'),
  ('buffalo', 'Murrah'),
  ('buffalo', 'Jaffarabadi'),
  ('buffalo', 'Surti'),
  ('buffalo', 'Mehsana'),
  ('buffalo', 'Nili-Ravi'),
  ('buffalo', 'Nagpuri'),
  ('buffalo', 'Pandharpuri'),
  ('buffalo', 'Toda'),
  ('buffalo', 'Bhadawari'),
  ('buffalo', 'Marathwadi'),
  ('buffalo', 'Chilika'),
  ('buffalo', 'Kalahandi')
on conflict (name) do nothing;
